### ISSUE TITLE
Allow enabled of eager execution

### ISSUE THREAD

**Issue by justin1121** [tf-encrypted/tf-encrypted#279]
Related https://github.com/mortendahl/tf-encrypted/issues/278

Right now tfe doesn't work out of the box with eager execution. One of the issues is that by default we use multiple devices to do our computation and currently eager execution doesn't work on more than one device. We'll have to do some other investigation to see if there are other problems.

I propose we add a function like `tfe.enable_eager_execution()` that modifies the configuration of tfe so that eager execution works.

**Comment by bendecoste** [comment]
I took a look at this.

### First pass issues
- [ ] If you `pip install tf-nightly-2.0` then `pip install tf-encrypted` you will get downgraded to tf 1.12.0
- [ ] The following classes we use are gone
  - [ ] `tf.ConfigProto` (removed in `11a1fc8cddc4e04dee1cd0155992fdd1bba6b111`)
  - [ ]`tf.train.Server`
  - [ ] `tf.Session`
    - moved to `tf.compat.v1.session`
    - this probably the most fundamental change that we need to adapt to, more details are outlined [here](https://github.com/tensorflow/community/pull/20)
- [ ] functions annotated with `@tf.function` cannot return a custom tensor type

As a user I would expect this to work
```python
@tf.function
def simple_private(x):
  return tfe.define_private_variable(x)

print(simple_private(tf.random.uniform((3,3))))
# should print encrypted values
```

But it does not!

```
[1]+  Stopped                 /usr/local/bin/nvim explore.py
(tf-2.0) bendecoste:2 (regression) $ python explore.py
WARNING:root:Falling back to insecure randomness since required custom op could not be found for the installed version of TensorFlow (2.0.0-preview). Fix this by compiling custom ops.
2019-01-23 14:19:38.452646: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 558, in make_tensor_proto
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 558, in <listcomp>
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 61, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got PondPrivateVariable(shape=(3, 3))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 491, in convert
    x = ops.convert_to_tensor_or_composite(x)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1433, in convert_to_tensor_or_composite
    value=value, dtype=dtype, name=name, as_ref=False)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1468, in internal_convert_to_tensor_or_composite
    value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1179, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 304, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 245, in constant
    allow_broadcast=True)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 283, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 562, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'tf_encrypted.protocol.pond.PondPrivateVariable'> to Tensor. Contents: PondPrivateVariable(shape=(3, 3)). Consider casting elements to a supported type.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "explore.py", line 25, in <module>
    print(simple_private(x))
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 383, in __call__
    self._initialize(args, kwds)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 355, in _initialize
    *args, **kwds))
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1097, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1322, in _maybe_define_function
    arg_names=arg_names), self._function_attributes)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 534, in func_graph_from_py_func
    func_outputs = nest.map_structure(convert, func_outputs)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/util/nest.py", line 409, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/util/nest.py", line 409, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 497, in convert
    (str(python_func), type(x)))
TypeError: To be compatible with tf.contrib.eager.defun, Python functions must return zero or more Tensors; in compilation of <function Function._defun_with_scope.<locals>.wrapped_fn at 0x126728730>, found return value of type <class 'tf_encrypted.protocol.pond.PondPrivateVariable'>, which is not a Tensor.
```

running in eager mode also does not work

```
2019-01-23 14:31:48.932250: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "explore.py", line 24, in <module>
    print(simple_private(x))
  File "explore.py", line 17, in simple_private
    return tfe.define_private_variable(x)
  File "/Users/bendecoste/code/tf-encrypted/2/tf_encrypted/protocol/pond.py", line 330, in define_private_variable
    x0 = factory.variable(v0)
  File "/Users/bendecoste/code/tf-encrypted/2/tf_encrypted/tensor/native.py", line 47, in variable
    return Variable(initial_value.value)
  File "/Users/bendecoste/code/tf-encrypted/2/tf_encrypted/tensor/native.py", line 406, in __init__
    self.variable = tf.Variable(initial_value, dtype=FACTORY.native_type, trainable=False)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 200, in __call__
    return cls._variable_v2_call(*args, **kwargs)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 194, in _variable_v2_call
    aggregation=aggregation)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 176, in <lambda>
    previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2525, in default_variable_creator_v2
    import_scope=import_scope, distribute_strategy=distribute_strategy)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 202, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 297, in __init__
    constraint=constraint)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 427, in _init_from_args
    graph_mode=self._in_graph_mode)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 69, in eager_safe_variable_handle
    container=container)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/ops/gen_resource_variable_ops.py", line 1254, in var_handle_op
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: /job:localhost/replica:0/task:0/device:CPU:2 unknown device. name: private-var/Variable/
```

**Comment by bendecoste** [comment]
I am sure there is more but it is looking like fixing the last two issues there will take some digging.

**Comment by bendecoste** [comment]
with `@tf.function` decorator i tried an alternative where we do not return a custom tensor

```
2019-01-23 14:36:19.511135: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "explore.py", line 27, in <module>
    print(simple_private(x))
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 452, in __call__
    return function_lib.defun(fn_with_cond)(*canon_args, **canon_kwds)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1071, in __call__
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1322, in _maybe_define_function
    arg_names=arg_names), self._function_attributes)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 530, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 450, in fn_with_cond
    inner_args, inner_kwds))
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1918, in cond
    return cond_v2.cond_v2(pred, true_fn, false_fn, name)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/ops/cond_v2.py", line 73, in cond_v2
    op_return_value=pred)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 530, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 448, in <lambda>
    lambda: self._stateless_fn(*inner_args, **inner_kwds),
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1071, in __call__
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1322, in _maybe_define_function
    arg_names=arg_names), self._function_attributes)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 530, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 298, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 523, in wrapper
    ), *args, **kwargs)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 295, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/var/folders/mj/5lqrbdls2p90vc_rghcy0n1m0000gn/T/tmp1zlgquft.py", line 3, in tf__simple_private
    x = tfe.define_private_variable(x)
  File "/Users/bendecoste/code/tf-encrypted/2/tf_encrypted/protocol/pond.py", line 330, in define_private_variable
    x0 = factory.variable(v0)
  File "/Users/bendecoste/code/tf-encrypted/2/tf_encrypted/tensor/native.py", line 47, in variable
    return Variable(initial_value.value)
  File "/Users/bendecoste/code/tf-encrypted/2/tf_encrypted/tensor/native.py", line 406, in __init__
    self.variable = tf.Variable(initial_value, dtype=FACTORY.native_type, trainable=False)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 200, in __call__
    return cls._variable_v2_call(*args, **kwargs)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 194, in _variable_v2_call
    aggregation=aggregation)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 58, in getter
    return captured_getter(captured_previous, **kwargs)
  File "/Users/bendecoste/anaconda3/envs/tf-2.0/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 361, in invalid_creator_scope
    "tf.function-decorated function tried to create "
ValueError: tf.function-decorated function tried to create variables on non-first call.

**Comment by bendecoste** [comment]
I looked into this a bit more today.  Was more focused on trying a solution than investigating the danger areas.

The general idea was that if we could subclass tensorflow tensors then perhaps this would "just work"

### Outcome

We would need to reinvent a bunch of existing functions, generally you do not directly instantiate tensors.  You use something like `tf.random.uniform`, or `tf.constant`, etc.  This wouldn't be a major blocker because we could define `tfe.random.uniform` that returns our custom type.  It is after all possible to define a tensor directly, you just don't really see it done very often.

### Custom class

The idea was to make something like this

```python
class MPCTensor(tf.Tensor)

    def __init__(self, shape):
        self.backing = tf.random.uniform(shape)

    def __add__(self, other):
        return self.backing + other.backing

    def __str__(self):
        return self.backing.__str__()
```

Which is quite close to what we do now, but inheriting from `tf.Tensor` instead of a custom type (`AbstractTensor`).

However, this also proved fruitless as the eager functions are expecting `EagerTensor`. 

`EagerTensor` is defined entirely in C, [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/eager/pywrap_tensor.cc)

It seems that `https://docs.python.org/3/c-api/typeobj.html#Py_TPFLAGS_BASETYPE` is preventing us from inheriting from this tensor.  It is also not public, you can access the type like this

```python
tensor = tf.random.uniform((3,3))
t = type(tensor)

class MPCTensor(t):
  pass
```

but I'd be hesitant to do this anyway, as it is not a public class.

Anyway, back to the drawing board on this.

**Comment by bendecoste** [comment]
This ended up not being a major issue using the serverDef proto api.

**Comment by bendecoste** [comment]
I'm no longer actively looking at this.

**Comment by justin1121** [comment]
I'm going to work on something related to my original proposal.

**Comment by zjn-code** [comment]
Eager execution is enabled in TFE based on TF2, it also supports building graph by `tfe.function`.
