### ISSUE TITLE
Can't turn setMonitorStats, TraceFlag, and DebugFlag on all at the same time

### ISSUE THREAD

**Issue by bendecoste** [tf-encrypted/tf-encrypted#407]
`setMonitorStats` and `setTFETraceFlag` can be on concurrently, but if you turn `setTFEDebugFlag` on, you will crash when running a graph

```
Traceback (most recent call last):
  File "ignite.py", line 21, in <module>
    prediction = mnist_model.private_predict(provide_input())
  File "/home/bendecoste/tf-encrypted/tf_encrypted/private_model.py", line 20, in private_predict
    sess.run(tf.global_variables_initializer())
  File "/home/bendecoste/tf-encrypted/tf_encrypted/session.py", line 107, in run
    feed_dict=feed_dict
  File "/home/bendecoste/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/bendecoste/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1075, in _run
    raise RuntimeError('Attempted to use a closed Session.')
```

`setTFEDebugFlag` alone seems okay, though.

**Comment by mortendahl** [comment]
I suggest we get rid of DebugFlag; may reintroduce it later but currently it's broken. wdyt @bendecoste?

**Comment by jvmancuso** [comment]
Agreed :)

**Comment by bendecoste** [comment]
works for me
