### ISSUE TITLE
Any workaround for InputLayer "not implemented"?

### ISSUE THREAD

**Issue by shreyansh26** [tf-encrypted/tf-encrypted#682]
I am trying to use the pre-trained VGG16 model of Keras and trying to convert it to a tfe model. All the layers in VGG16 are implemented in TFE, except the first InputLayer. Is there any workaround for it? Any way I can still use that model?

**Comment by mortendahl** [comment]
cc @jvmancuso @yanndupis

**Comment by shreyansh26** [comment]
Well the InputLayer() is also implemented but with the `keras.applications.vgg16.VGG16(include_top=True, weights='imagenet', input_tensor=None, input_shape=None, pooling=None, classes=1000)`, it gives an error

```
Traceback (most recent call last):
  File "test_vgg.py", line 86, in <module>
    tfe_model = tfe.keras.models.clone_model(model)
  File "/usr/local/lib/python3.6/dist-packages/tf_encrypted/keras/models/sequential.py", line 244, in clone_model
    tfe_model = model_from_config(config)
  File "/usr/local/lib/python3.6/dist-packages/tf_encrypted/keras/models/sequential.py", line 226, in model_from_config
    tfe_model.add(tfe_layer)
  File "/usr/local/lib/python3.6/dist-packages/tf_encrypted/keras/models/sequential.py", line 58, in add
    name=layer.name + '_input')
  File "/usr/local/lib/python3.6/dist-packages/tf_encrypted/keras/engine/input_layer.py", line 159, in Input
    input_tensor=tensor)
  File "/usr/local/lib/python3.6/dist-packages/tf_encrypted/keras/engine/input_layer.py", line 51, in __init__
    raise NotImplementedError()
```

**Comment by jvmancuso** [comment]
Ah, the problem here is that we've only tested converting Sequential models via clone_model, and using the InputLayer isn't necessary in those cases.  We should be able to implement that layer, but there will be some complications around the input shape.  We don't yet accept None shapes for inputs, so it will be difficult to have parity with these pretrained models.  As far as I know, this is because we need fully-defined shapes when we're generating triples offline.  @mortendahl might be able to clarify more here.  I do think we'll need to fix that for using online triples.

**Comment by mortendahl** [comment]
> As far as I know, this is because we need fully-defined shapes when we're generating triples offline. @mortendahl might be able to clarify more here. I do think we'll need to fix that for using online triples.

Indeed, it currently has to do with the triples, but could in principle also be needed by other protocols due to eg packing and data layout in homomorphic encryption. It would make sense to allow partial shapes for some protocols though, as long as this doesn't give them special status wrt other components of TFE (ie supporting partial shapes should be a convenience, not a requirement).

**Comment by mortendahl** [comment]
Did you find a workaround @shreyansh26?

**Comment by shreyansh26** [comment]
No, nothing yet for the pretrained Keras models. I tried removing the input layer, as Keras models are customizable and then assigning the weights to the lower layers but it still gives an error. Something related to the shape in which the next Conv_2D layer is expecting the input as.
 I have left it for the time being and training my own model now, which is working fine.

**Comment by shreyansh26** [comment]
Hi @mortendahl, could you take a look at #705 if you could help me out?
