### ISSUE TITLE
Unable to run federated learning example. Getting "From /job:tfe/replica:0/task:0: ./data/train.tfrecord; No such file or directory" error

### ISSUE THREAD

**Issue by sug4ndh** [tf-encrypted/tf-encrypted#827]
Hi,

I am trying to execute federated learning example and for this purpose, I have created 7 vms which have access to each other. I downloaded the data on each of the data-owners using the download.py script.

My config.json has the following contents:
```
{
"model-owner": "192.168.56.112:9003",
"data-owner-0": "192.168.56.113:9002",
"data-owner-1": "192.168.56.110:9001",
"data-owner-2": "192.168.56.108:9002",
"server0": "192.168.56.109:9003",
"server1": "192.168.56.111:9003",
"server2": "192.168.56.114:9003"
}
```

In each of the machines, I run the following:
```
python3 -m tf_encrypted.player model-owner --config config.json
python3 -m tf_encrypted.player data-owner-0 --config config.json
python3 -m tf_encrypted.player data-owner-1 --config config.json
python3 -m tf_encrypted.player data-owner-2 --config config.json
python3 -m tf_encrypted.player server0 --config config.json
python3 -m tf_encrypted.player server1 --config config.json
python3 -m tf_encrypted.player server2 --config config.json
```

But when I execute run.py, I get the following error:
```
Iteration 0
Traceback (most recent call last):
  File "/home/sug/demo/env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/sug/demo/env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/sug/demo/env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: From /job:tfe/replica:0/task:0:
./data/train.tfrecord; No such file or directory
	 [[{{node local-computation_3/validate/IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 206, in <module>
    sess.run(iteration_op, tag="iteration")
  File "/home/sug/demo/env/lib/python3.6/site-packages/tf_encrypted/session.py", line 93, in run
    feed_dict=feed_dict
  File "/home/sug/demo/env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/sug/demo/env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/sug/demo/env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/sug/demo/env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: From /job:tfe/replica:0/task:0:
./data/train.tfrecord; No such file or directory
	 [[node local-computation_3/validate/IteratorGetNext (defined at /home/sug/demo/env/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'local-computation_3/validate/IteratorGetNext':
  File "run.py", line 198, in <module>
    iteration_op = model_owner.update_model(*aggregated_model_grads)
  File "/home/sug/demo/env/lib/python3.6/site-packages/tf_encrypted/protocol/pond/pond.py", line 527, in compute_func_wrapper
    **kwargs,
  File "/home/sug/demo/env/lib/python3.6/site-packages/tf_encrypted/protocol/pond/pond.py", line 624, in define_local_computation
    outputs = computation_fn(*inputs)
  File "run.py", line 119, in update_model
    x, y = self._build_data_pipeline()
  File "run.py", line 96, in _build_data_pipeline
    return iterator.get_next()
  File "/home/sug/demo/env/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 426, in get_next
    name=name)
  File "/home/sug/demo/env/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2518, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/home/sug/demo/env/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/sug/demo/env/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/sug/demo/env/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/sug/demo/env/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/sug/demo/env/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```

My vms are running Ubuntu 18.04. My tensorflow version is 1.15.4 and tf-encrypted version is 0.5.9 on all the vms. 

What is causing the issue here as data folder is present in all of the data-owners? 

Any help is really appreciated.

Thanks!

**Comment by jvmncs** [comment]
It looks the data owner corresponding to `/job:tfe/replica:0/task:0` from the config is unable to find the path for your TF Records (presumable this happens in a `tfe.local_computation`. I would suggest that you double check that this file is reachable from the path when/wherever that `local_computation` is being executed.

**Comment by zicofish** [comment]
Close this now. Please open a new one if case of further issue.
