### ISSUE TITLE
TypeError: can only concatenate list (not "TensorShapeV1") to list. (An error in sample_seeded_uniform)

### ISSUE THREAD

**Issue by qxzhou1010** [tf-encrypted/tf-encrypted#877]
Hi, I am studying the `aby3_test.py`. When I run the test about `mul` , such as: `test_mul_private_public` and `test_mul_private_private`. I will encounter this error: **`TypeError: can only concatenate list (not "TensorShapeV1") to list`** . The full error stack is following:

```
ERROR: test_mul_private_public (__main__.TestABY3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "aby3_test.py", line 188, in test_mul_private_public
    z1 = y * x  # mul_public_private
  File "/Users/*/tfes/tf-encrypted/tf_encrypted/protocol/aby3/aby3_tensors.py", line 187, in __mul__
    return self.prot.mul(self, other)
  File "/Users/*/tfes/tf-encrypted/tf_encrypted/protocol/protocol.py", line 107, in cache_nodes
    result = func(self, *args, **kwargs)
  File "/Users/*/tfes/tf-encrypted/tf_encrypted/protocol/aby3/aby3.py", line 1376, in mul
    return self.dispatch("mul", x, y)
  File "/Users/*/tfes/tf-encrypted/tf_encrypted/protocol/aby3/aby3.py", line 2132, in dispatch
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/Users/*/tfes/tf-encrypted/tf_encrypted/protocol/aby3/aby3.py", line 2525, in _mul_public_private
    z = prot.truncate(z) if x.is_scaled and y.is_scaled else z
  File "/Users/*/tfes/tf-encrypted/tf_encrypted/protocol/protocol.py", line 107, in cache_nodes
    result = func(self, *args, **kwargs)
  File "/Users/*/tfes/tf-encrypted/tf_encrypted/protocol/aby3/aby3.py", line 1555, in truncate
    return self.dispatch("truncate_" + method, x, amount)
  File "/Users/*/tfes/tf-encrypted/tf_encrypted/protocol/aby3/aby3.py", line 2132, in dispatch
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/Users/*/tfes/tf-encrypted/tf_encrypted/protocol/aby3/aby3.py", line 2796, in _truncate_heuristic_private
    z = prot.truncate_msb0(y, method="secureq8", amount=amount)
  File "/Users/*/tfes/tf-encrypted/tf_encrypted/protocol/protocol.py", line 107, in cache_nodes
    result = func(self, *args, **kwargs)
  File "/Users/*/tfes/tf-encrypted/tf_encrypted/protocol/aby3/aby3.py", line 1564, in truncate_msb0
    return self.dispatch("truncate_msb0_" + method, x, amount)
  File "/Users/*/tfes/tf-encrypted/tf_encrypted/protocol/aby3/aby3.py", line 2132, in dispatch
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/Users/*/tfes/tf-encrypted/tf_encrypted/protocol/aby3/aby3.py", line 2983, in _truncate_msb0_secureq8_private
    [4] + shape, prot.pairwise_keys()[2][1] + prot.pairwise_nonces()[2]
TypeError: can only concatenate list (not "TensorShapeV1") to list
```

Finallay, I found problem occurs in this function `_truncate_msb0_secureq8_private` , the detail is ：

```
 with tf.device(prot.servers[2].device_name):
            # print("shape: ", shape)
            randoms02_on_2 = ifactory.sample_seeded_uniform(
                [4] + shape, prot.pairwise_keys()[2][1] + prot.pairwise_nonces()[2]
            )
```
Specifically, it is `[4] + shape`  that causes the error. Also, I found that `[4] + shape` is used in many places where `sample_seeded_uniform` is called. I read the code of `sample_seeded_uniform`, the first parameter just a shape. So,

-  **What is the purpose of  using `[4] + shape` as the first parameter for `sample_seeded_uniform`?**
- **How can I fix this error? so that `mul` related tests can pass normally..**

Note that I am using 0.8.0 with TF1.

**Comment by zjn-code** [comment]
We use `[4] + shape` in `sample_seeded_uniform` to get 4 seeded random tensor with shape  of `shape`.
`[4] + shape` maybe fail in some version of tensorflow, commit #864 fix a similar problem.

**Comment by qxzhou1010** [comment]
> We use `[4] + shape` in `sample_seeded_uniform` to get 4 seeded random tensor with shape of `shape`. `[4] + shape` maybe fail in some version of tensorflow, commit #864 fix a similar problem.

Thanks for your reply. I will try to use the solution of commit #864 to fix this error.
