### ISSUE TITLE
AttributeError: module 'tf_encrypted' has no attribute 'EagerLocalConfig'

### ISSUE THREAD

**Issue by Muhammadkamrul** [tf-encrypted/tf-encrypted#897]
Version:
protobuf==3.20.3
tensorflow==2.9.1

 kamrul@ircisshpc3:~/Documents/kamrul_files/Fl_sec_tf1$ python3 main.py
Traceback (most recent call last):
  File "/home/kamrul/Documents/kamrul_files/Fl_sec_tf1/main.py", line 201, in <module>
    app.run(main)
  File "/home/kamrul/anaconda3/envs/py39/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/kamrul/anaconda3/envs/py39/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/kamrul/Documents/kamrul_files/Fl_sec_tf1/main.py", line 141, in main
    config = tfe.EagerLocalConfig(players + data_owners)
AttributeError: module 'tf_encrypted' has no attribute 'EagerLocalConfig'

**Comment by Muhammadkamrul** [comment]
I solved it by changing EagerLocalConfig to LocalConfig. I think EagerLocalConfig is not available in newer versions.
